### PR TITLE
Update to 1.7.9

### PR DESCRIPTION
**Pull request by AnthonyAMC**
Update Vault to use LATEST

### CODE REVIEW

**Comment by just-push-it** [comment]
Just a request, please make sure the PR builds before you submit it. :)

**Comment by AnthonyAMC** [comment]
It did when i submitted it.
http://ci.mineconomy.org/job/NoItem-Local/16/console
The herocraft folks have been privatizing mostly all of their projects... Vault is still on github so you're able to make a local repo on your jenkins and build from that. No need to go to theyetis repo. I already build Vault locally for just this reason.

**Comment by just-push-it** [comment]
ahh I see. Well, I just updated to build with their repo. You can change it to build with yours in the future if you wish haha.

**Comment by AnthonyAMC** [comment]
It's like Sleaker has random fits of paranoia and hides everything... leaving only what is necessary. Random factoid... ci.milkbowl.net does a redirect to an ad site. HA! Gotta get that ad revenue from dead links.

**Pull request merged**
