### PR TITLE
Permissions Improvement - Data value overriding

### PR DESCRIPTION
**Pull request by nvx**
I'm trying to enable 7493:1, but disable 7493 with all other data values.

```
  noitem.nohold.7493.1: false
  noitem.nocraft.7493.1: false
  noitem.nouse.7493.1: false
  noitem.nohave.7493.1: false
  noitem.nohold.7493.all: true
  noitem.nocraft.7493.all: true
  noitem.nouse.7493.all: true
  noitem.nohave.7493.all: true
```

Are the permission nodes I have, but this does not achieve the desired effect. Thoughts on achieving such a goal without listing all 4000 odd possible data values?

### CODE REVIEW

**Comment by nvx** [comment]
I finally got a bit of time and implemented this myself. I havent tested with PermsAsWhiteList set, but it should work as expected.

Logic is the most-specific defined permissions node takes precedence over other more general nodes.

Enjoy. :)

**Comment by just-push-it** [comment]
Thanks for this :) I really have not had time nor motivation to fix anything lately..

**Pull request merged**
